Handle IgnoreMissingAssembliesDuringRegistration missing in .NET 7
NSApplication.IgnoreMissingAssembliesDuringRegistration is not
available for the macOS workload in .NET 7. Add an ifdef to avoid
this being used if the code is being compiled with .NET 7 or greater.

xwt/Xwt.XamMac/Xwt.Mac/NSApplicationInitializer.cs(44,19): error CS0117:
'NSApplication' does not contain a definition for
'IgnoreMissingAssembliesDuringRegistration'